name: Release

on:
  push:
    tags:
      - "simple-rules-*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew publish --no-daemon
      - name: Update release notes
        uses: BobAnkh/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat!:Breaking Change,feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
      - name: Release
        uses: softprops/action-gh-release@v1
